name: 'InfluxDB Writer'
description: 'Parses workflow data and writes the data into a preconfigured InfluxDB instance.'
inputs:
  github_access_token:
    description: 'Token to access the API'
    required: true
  repository:
    description: 'Name of the repository where the workflow is'
    required: true
    default: "${{ github.repository }}"
  workflow_run_id:
    description: 'ID of the workflow where data is to be gathered.'
    required: true
    default: "${{ github.run_id }}"
  influxdb_url:
    description: 'InfluxDB URL'
    required: true
  influxdb_bucket:
    description: 'InfluxDB bucket'
    required: true
  influxdb_org:
    description: 'InfluxDB organization'
    required: true
  influxdb_token:
    description: 'InfluxDB access token'
    required: true

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
            export OWNER="$(echo "${{ inputs.repository }}" | awk -F / '{print $1}' | sed -e "s/:refs//")"
            export REPO="$(echo "${{ inputs.repository }}" | awk -F / '{print $2}' | sed -e "s/:refs//")"
            echo "REPOSITORY_OWNER=$OWNER" >> $GITHUB_ENV
            echo "REPOSITORY_NAME=$REPO" >> $GITHUB_ENV
    - shell: bash
      run: ${{ github.action_path }}/write.sh
      env:
        GITHUB_ACCESS_TOKEN: ${{ inputs.github_access_token }}
        OWNER: "${{ env.REPOSITORY_OWNER }}"
        REPO: "${{ env.REPOSITORY_NAME }}"
        WORKFLOW_RUN_ID: ${{ inputs.workflow_run_id }}
        INFLUXDB_V2_URL: "${{ inputs.influxdb_url }}"
        INFLUXDB_V2_BUCKET: "${{ inputs.influxdb_bucket }}"
        INFLUXDB_V2_ORG: "${{ inputs.influxdb_org }}"
        INFLUXDB_V2_TOKEN: "${{ inputs.influxdb_token }}"
