
docker run \
    -e GH_TOKEN=$GITHUB_ACCESS_TOKEN \
    -e REPO=$REPO \
    -e OWNER=$OWNER \
    -e WORKFLOW_RUN_ID=$WORKFLOW_RUN_ID \
    -e INFLUXDB_V2_URL=$INFLUXDB_V2_URL \
    -e INFLUXDB_V2_BUCKET=$INFLUXDB_V2_BUCKET \
    -e INFLUXDB_V2_ORG=$INFLUXDB_V2_ORG \
    -e INFLUXDB_V2_TOKEN=$INFLUXDB_V2_TOKEN \
    -e INFLUXDB_V2_TIMEOUT=$INFLUXDB_V2_TIMEOUT \
    -e INFLUXDB_V2_VERIFY_SSL=$INFLUXDB_V2_VERIFY_SSL \
    -e INFLUXDB_V2_SSL_CA_CERT=$INFLUXDB_V2_SSL_CA_CERT \
    -e INFLUXDB_V2_CERT_FILE=$INFLUXDB_V2_CERT_FILE \
    -e INFLUXDB_V2_CERT_KEY_FILE=$INFLUXDB_V2_CERT_KEY_FILE \
    -e INFLUXDB_V2_CERT_KEY_PASSWORD=$INFLUXDB_V2_CERT_KEY_PASSWORD \
    -e INFLUXDB_V2_CONNECTION_POOL_MAXSIZE=$INFLUXDB_V2_CONNECTION_POOL_MAXSIZE \
    -e INFLUXDB_V2_AUTH_BASIC=$INFLUXDB_V2_AUTH_BASIC \
    pleksi/influxdb-write-action
